import type { Metadata } from "next";
import { Catamaran, Aladin, Amaranth, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const aladin = Aladin(
  {
    subsets: ["latin"],
    variable: "--font-aladin",
    display: "swap",
    weight: ["400"],
  }
)

const amaranth = Amaranth(
  {
    subsets: ["latin"],
    variable: "--font-amaranth",
    display: "swap",
    weight: ["400"],
  }
)

const catamaran = Catamaran(
  {
    subsets: ["latin"],
    variable: "--font-cat",
    display: "swap",
    weight: ["100"],
  }
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${catamaran.variable} ${inter.variable} ${amaranth.className} ${aladin.variable}`}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
